import Head from 'next/head'
import { MainWrapper } from '../components'

export default function Home() {
  return (
    <MainWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Hello world!</h1>
    </MainWrapper>
  )
}
